### ISSUE TITLE
 ImportError: No module named req

### ISSUE THREAD

**Issue by ju2wheels** [spotify/pyfg#28]
Install error:

```
Collecting pyFG

  Downloading pyfg-0.50.tar.gz

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-GOjqC9/pyFG/setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
```

From upstream, you should not be depending on this pip internal: https://github.com/pypa/pip/issues/3240

**Comment by pffs** [comment]
Same issue, had to downgrade to pip9 in order to install.

Probably should rework the setup.py to not depend on pip internals, but changing the import to the following would resolve it:
```python
try: # for pip >= 10
    from pip._internal.req import parse_requirements
except ImportError: # for pip <= 9.0.3
    from pip.req import parse_requirements
```
I submitted a PR for it if you want to go that route.

**Comment by RichardBotham** [comment]
All, since python2.0 is now deprecated will we get an update on 'pip.req' and 'pyfg' to work with python 3.x.?
