### ISSUE TITLE
pip install pyfg failing

### ISSUE THREAD

**Issue by hxvxt2** [spotify/pyfg#46]
I am trying to install `pyfg` using `pipenv` (python 3.9) but the command fails with the following error:

`>pipenv install pyfg`
```
Installing pyfg…
Error:  An error occurred while installing pyfg!
Error text: Collecting pyfg
  Using cached pyfg-0.50.tar.gz (9.1 kB)

    ERROR: Command errored out with exit status 1:
     command: /Users/vikrant.tyagi/.virtualenvs/fortios-automation-uy-maohS/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kh/m16w2sgn10jd06jfxd58wl_c_2h4vh/T/pip-install-_8rwn0my/pyfg/setup.py'"'"'; __file__='"'"'/private/var/folders/kh/m16w2sgn10jd06jfxd58wl_c_2h4vh/T/pip-install-_8rwn0my/pyfg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/kh/m16w2sgn10jd06jfxd58wl_c_2h4vh/T/pip-pip-egg-info-c6kf6k4d
         cwd: /private/var/folders/kh/m16w2sgn10jd06jfxd58wl_c_2h4vh/T/pip-install-_8rwn0my/pyfg/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kh/m16w2sgn10jd06jfxd58wl_c_2h4vh/T/pip-install-_8rwn0my/pyfg/setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

This is likely caused by a bug in pyfg. Report this to its maintainers.
✘ Installation Failed
```

**Comment by hxvxt2** [comment]
Update: It's failing for 2.7 and 3.7 as well.

**Comment by tirkarthi** [comment]
This will be fixed once one of the below is merged

https://github.com/spotify/pyfg/pull/35
https://github.com/spotify/pyfg/pull/44
