### ISSUE TITLE
Paramiko disconnects with EOFError

### ISSUE THREAD

**Issue by adieball** [spotify/pyfg#6]
Hi

I tried to connect to a FG with plan basic Paramiko and struggled. I then tested with your module and basically got the same error:

```
from pyFG import FortiOS
d = FortiOS('10.8.20.102')
d.open()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pyFG/fortios.py", line 94, in open
    self.ssh.connect(**cfg)
  File "build/bdist.macosx-10.11-intel/egg/paramiko/client.py", line 325, in connect
    t.start_client()
  File "build/bdist.macosx-10.11-intel/egg/paramiko/transport.py", line 492, in start_client
    raise e
EOFError
```

Any idea what this could be? It looks like it's only happening with FortiOS Devices, I can connect to normal Linux hosts without any issues.

**Comment by dbarrosop** [comment]
Have you tried with paramiko directly with the same results? Could you open an issue with them?

**Comment by adieball** [comment]
Hi

i did some further troubleshooting and it really looks like a paramiko issue.
